export type UsRegion = "northeast_midwest" | "south" | "west";

/** Three IRL buckets for presidential community (40%) regional aggregation. */
export const STATE_REGION: Record<string, UsRegion> = {
  CT: "northeast_midwest",
  IL: "northeast_midwest",
  DC: "south",
  IN: "northeast_midwest",
  IA: "northeast_midwest",
  KS: "northeast_midwest",
  ME: "northeast_midwest",
  MA: "northeast_midwest",
  MI: "northeast_midwest",
  MN: "northeast_midwest",
  MO: "northeast_midwest",
  NE: "northeast_midwest",
  NH: "northeast_midwest",
  NJ: "northeast_midwest",
  NY: "northeast_midwest",
  ND: "northeast_midwest",
  OH: "northeast_midwest",
  PA: "northeast_midwest",
  RI: "northeast_midwest",
  SD: "northeast_midwest",
  VT: "northeast_midwest",
  WI: "northeast_midwest",
  AL: "south",
  AR: "south",
  DE: "south",
  FL: "south",
  GA: "south",
  KY: "south",
  LA: "south",
  MD: "south",
  MS: "south",
  NC: "south",
  OK: "south",
  SC: "south",
  TN: "south",
  TX: "south",
  VA: "south",
  WV: "south",
  AK: "west",
  AZ: "west",
  CA: "west",
  CO: "west",
  HI: "west",
  ID: "west",
  MT: "west",
  NV: "west",
  NM: "west",
  OR: "west",
  UT: "west",
  WA: "west",
  WY: "west",
};

export function regionForState(state: string): UsRegion | undefined {
  return STATE_REGION[state];
}
